name: Trading agent

on:
  schedule:
    - cron: "0 13 * * 1-5"  # 9am EST (13:00 UTC)
    - cron: "0 15 * * 1-5"  # 11am EST (15:00 UTC)
    - cron: "0 17 * * 1-5"  # 1pm EST (17:00 UTC)
    - cron: "0 19 * * 1-5"  # 3pm EST (19:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-trading-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run trading agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: ${{ vars.MODEL }}
        run: npm start

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-logs-${{ github.run_id }}
          path: agent.log
          retention-days: 30

      - name: Commit portfolio changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add portfolio.json agent.log thread.json README.md
          git diff --staged --quiet || git commit -m ":loud_sound: Update portfolio after trading session [skip ci]"
          git push
